// GENERATED by scripts/build-assets.mjs — do not edit by hand.
// Regenerate with `pnpm assets`.

/** Widths emitted for every source below. Mirrors next.config imageSizes+deviceSizes. */
export const VARIANT_WIDTHS = [384, 640, 828, 1200] as const

/** Sources that have `<name>-<width>.webp` siblings on disk. */
export const VARIANT_SOURCES: ReadonlySet<string> = new Set([
  "/an2.webp",
  "/as.webp",
  "/av.webp",
  "/campus.webp",
  "/event.webp",
  "/events-hero-mobile.webp",
  "/events-hero.webp",
  "/last.webp",
  "/p2.webp",
  "/plan.webp",
  "/restar.webp",
  "/talent-hero.webp",
  "/talents-hero-mobile.webp",
])
